Build and Publish

diff --git a/.github/workflows/drbd-utils-build-and-publish .yml b/.github/workflows/drbd-utils-build-and-publish .yml
--- a/.github/workflows/drbd-utils-build-and-publish .yml
+++ b/.github/workflows/drbd-utils-build-and-publish .yml
@@ -57,13 +57,13 @@ jobs:
           ./autogen.sh || true
           ./configure || true
 
-      - name: Verify Makefile existence
-        run: |
-          cd drbd-utils
-          if [ ! -f Makefile ]; then
-            echo "Makefile not found!"
-            exit 1
-          fi
+      # - name: Verify Makefile existence
+      #   run: |
+      #     cd drbd-utils
+      #     if [ ! -f Makefile ]; then
+      #       echo "Makefile not found!"
+      #       exit 1
+      #     fi
 
       - name: Build package
         run: |
