Build and Publish

diff --git a/.github/workflows/linstor-api-py-build-and-publish .yml b/.github/workflows/linstor-api-py-build-and-publish .yml
--- a/.github/workflows/linstor-api-py-build-and-publish .yml
+++ b/.github/workflows/linstor-api-py-build-and-publish .yml
@@ -43,28 +43,22 @@ jobs:
             cargo \
             rustc
 
-      - name: Clone DRBD repository
+      - name: Clone linstor-api-py repository
         run: |
           git clone https://github.com/LINBIT/linstor-api-py.git
           cd linstor-api-py
           git pull
 
-      - name: Generate configuration files
+      - name: Build LINSTOR API Py package
         run: |
           cd linstor-api-py
-          if [ -f ./configure ]; then
-            echo "Configure script found, running configure."
-            ./configure
-          else
-            echo "Configure script not found, checking for other setup scripts."
-            # Add additional setup steps here if necessary
-          fi
+          make -C linstor-common || true  # Attempt to make in linstor-common, allowing failure
+          python3 setup.py build
 
-      - name: Build package
+      - name: Install LINSTOR API Py package
         run: |
           cd linstor-api-py
-          make
-          sudo make install
+          sudo python3 setup.py install
       
       - name: Build Source Package
         run: |
diff --git a/.github/workflows/linstor-client-build-and-publish .yml b/.github/workflows/linstor-client-build-and-publish .yml
--- a/.github/workflows/linstor-client-build-and-publish .yml
+++ b/.github/workflows/linstor-client-build-and-publish .yml
@@ -43,28 +43,29 @@ jobs:
             cargo \
             rustc
 
+      - name: Clone LINSTOR API Py repository
+        run: |
+          git clone https://github.com/LINBIT/linstor-api-py.git
+          cd linstor-api-py
+          git pull
+      
+      - name: Build and Install LINSTOR API Py package
+        run: |
+          cd linstor-api-py
+          make -C linstor-common || true  # Attempt to make in linstor-common, allowing failure
+          python3 setup.py build
+          sudo python3 setup.py install
+
       - name: Clone Linstor-Client repository
         run: |
           git clone https://github.com/LINBIT/linstor-client.git
           cd linstor-client
           git pull
 
-      - name: Generate configuration files
+      - name: Build LINSTOR Client package
         run: |
           cd linstor-client
-          if [ -f ./configure ]; then
-            echo "Configure script found, running configure."
-            ./configure
-          else
-            echo "Configure script not found, checking for other setup scripts."
-            # Add additional setup steps here if necessary
-          fi
-
-      - name: Build package
-        run: |
-          cd linstor-client
-          make
-          sudo make install
+          python3 setup.py build_man
       
       - name: Build Source Package
         run: |
diff --git a/.github/workflows/linstor-gateway-build-and-publish .yml b/.github/workflows/linstor-gateway-build-and-publish .yml
--- a/.github/workflows/linstor-gateway-build-and-publish .yml
+++ b/.github/workflows/linstor-gateway-build-and-publish .yml
@@ -43,39 +43,44 @@ jobs:
             cargo \
             rustc
 
-      - name: Clone DRBD repository
+      - name: Clone LINSTOR API Py repository
+        run: |
+          git clone https://github.com/LINBIT/linstor-api-py.git
+          cd linstor-api-py
+          git pull
+    
+      - name: Build and Install LINSTOR API Py package
+        run: |
+          cd linstor-api-py
+          make -C linstor-common || true  # Attempt to make in linstor-common, allowing failure
+          python3 setup.py build
+          sudo python3 setup.py install
+    
+      - name: Clone LINSTOR Client repository
+        run: |
+          git clone https://github.com/LINBIT/linstor-client.git
+          cd linstor-client
+          git pull
+    
+      - name: Build and Install LINSTOR Client package
+        env:
+          PYTHONPATH: "../linstor-api-py:."
+        run: |
+          cd linstor-client
+          python3 setup.py build_man
+          sudo python3 setup.py install
+    
+      - name: Clone LINSTOR Gateway repository
         run: |
           git clone https://github.com/LINBIT/linstor-gateway.git
           cd linstor-gateway
           git pull
-
-      - name: Generate configuration files
-        run: |
-          cd linstor-gateway
-          if [ -f ./configure ]; then
-            echo "Configure script found, running configure."
-            ./configure
-          else
-            echo "Configure script not found, checking for other setup scripts."
-            # Add additional setup steps here if necessary
-          fi
-
-      - name: Build package
-        run: |
-          cd linstor-gateway
-          make
-          sudo make install
-      
-      - name: Build Source Package
-        run: |
-          cd linstor-gateway
-          dpkg-buildpackage -us -uc -S
-      
-      - name: Build Binary Package
+    
+      - name: Build and Package LINSTOR Gateway
         run: |
           cd linstor-gateway
           dpkg-buildpackage -us -uc -b
-
+    
       - name: Install PackageCloud CLI
         run: |
           sudo gem install package_cloud
diff --git a/.github/workflows/linstor-server-build-and-publish .yml b/.github/workflows/linstor-server-build-and-publish .yml
--- a/.github/workflows/linstor-server-build-and-publish .yml
+++ b/.github/workflows/linstor-server-build-and-publish .yml
@@ -14,6 +14,7 @@ jobs:
       matrix:
         os: ["noble", "jammy"]
     runs-on: ubuntu-latest
+    timeout-minutes: 60
 
     steps:
       - name: Checkout repository
@@ -43,39 +44,40 @@ jobs:
             cargo \
             rustc
 
-      - name: Clone DRBD repository
+      - name: Clone and Build LINSTOR API Py
+        run: |
+          git clone https://github.com/LINBIT/linstor-api-py.git
+          cd linstor-api-py
+          git pull
+          make -C linstor-common || true  # Attempt to make in linstor-common, allowing failure
+          python3 setup.py build
+          sudo python3 setup.py install
+    
+      - name: Clone and Build LINSTOR Client
+        run: |
+          git clone https://github.com/LINBIT/linstor-client.git
+          cd linstor-client
+          git pull
+          PYTHONPATH="../linstor-api-py:." python3 setup.py build_man
+          sudo python3 setup.py install
+    
+      - name: Clone and Build LINSTOR Server
         run: |
           git clone https://github.com/LINBIT/linstor-server.git
           cd linstor-server
           git pull
-
-      - name: Generate configuration files
-        run: |
-          cd linstor-server
-          if [ -f ./configure ]; then
-            echo "Configure script found, running configure."
-            ./configure
-          else
-            echo "Configure script not found, checking for other setup scripts."
-            # Add additional setup steps here if necessary
-          fi
-
-      - name: Build package
-        run: |
-          cd linstor-server
+          ./autogen.sh  # Ensure autogen.sh is run if it exists
+          ./configure   # Ensure configure is run if it exists
           make
           sudo make install
-      
-      - name: Build Source Package
+    
+      - name: Clone and Build LINSTOR Gateway
         run: |
-          cd linstor-server
-          dpkg-buildpackage -us -uc -S
-
-      - name: Build Binary Package
-        run: |
-          cd linstor-server
+          git clone https://github.com/LINBIT/linstor-gateway.git
+          cd linstor-gateway
+          git pull
           dpkg-buildpackage -us -uc -b
-
+    
       - name: Install PackageCloud CLI
         run: |
           sudo gem install package_cloud
