Build and Publish repo

diff --git a/.github/workflows/linstor-server-build-and-publish .yml b/.github/workflows/linstor-server-build-and-publish .yml
--- a/.github/workflows/linstor-server-build-and-publish .yml
+++ b/.github/workflows/linstor-server-build-and-publish .yml
@@ -84,7 +84,14 @@ jobs:
           cd linstor-server
           ./gradlew wrapper --gradle-version 7.3.3
           ./gradlew getProtoc 
-          ./gradlew build
+          make build || echo "Failed to build. Checking debug info..."
+
+      - name: Debug Info
+        if: failure()
+        run: |
+          cd linstor-server
+          # Print Gradle debug logs
+          ./gradlew --stacktrace --debug
 
       - name: Build LINSTOR Server package
         run: |
